Issue #52 receiving error messages
google/project-OCEAN pull request #54
Opened 2020-11-17 21:36 UTC by frankyan1119

Fixes #<issue_number_goes_here>

**client.insert_rows_json(table, json_row)** keeps returning this error:

**"This json row did not load to BigQuery: [........] and threw this error: "**

2020-11-17 21:38 UTC, frankyan1119 commented
@googlebot I signed it!

2020-11-17 22:13 UTC, nyghtowl requested changes

2020-11-17 22:13 UTC, nyghtowl commented on 2-transform-data/bq_ingestion/extract_msgs_test.py
> +    @mock.patch("google.cloud.storage.Client")
Change to google.cloud.bigquery.Client and mock.patch any other objects that are used in the function here like Table.

2020-11-17 22:13 UTC, nyghtowl commented on 2-transform-data/bq_ingestion/extract_msgs_test.py
> +    def create_client_mock(self, Client):
pass in any variables you want to use in the mock before the objects you pass in. So if you want to simulate the table id you create, pass in the variable like `(self, table_id, Client)`

2020-11-17 22:13 UTC, nyghtowl commented on 2-transform-data/bq_ingestion/extract_msgs_test.py
> +
Simulate any function calls and returns you need from the Client an other objects like `client.get_table(table_id)` would become `client.get_table.return_value = table_id`

2020-11-17 22:13 UTC, nyghtowl commented on 2-transform-data/bq_ingestion/extract_msgs_test.py
>      def test_store_in_bigquery(self):
Thanks for keeping to the test structure.

2022-12-12 23:55 UTC, glasnt commented
Closing, see #97

2022-12-12 23:55 UTC, closed without merging